/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.example {
    export class ExampleUIUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("example/ExampleUI");
        }
    }
    REG("ui.example.ExampleUIUI",ExampleUIUI);
    export class LoadingUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("example/Loading");
        }
    }
    REG("ui.example.LoadingUI",LoadingUI);
}