/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class LoadingUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/Loading");
        }
    }
    REG("ui.test.LoadingUI",LoadingUI);
    export class MainEntryUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("test/MainEntry");
        }
    }
    REG("ui.test.MainEntryUI",MainEntryUI);
}