export default class ProductKey {
    static readonly zs_version = 0;
    static readonly zs_switch = 0;
    static readonly zs_start_game_video_switch = 0; // 开局看视频
    static readonly zs_banner_vertical_enable = 0; //按钮上移开关 暂时没用上 用的zs_button_delay_time
    static readonly zs_jump_switch = 0; // 导出总开关
    static readonly zs_full_screen1_jump = 0;
    static readonly zs_full_screen2_jump = 0;
    static readonly zs_finish_jump = 0; // 结算页导出
    static readonly zs_history_list_jump = 0; // 假退出 游戏页、结算页才有
    static readonly zs_auto_full_screen_jump_switch = 0; // 开局弹全屏1、2界面
    static readonly zs_auto_jump_switch = 0; // 全屏界面自动弹一个导出
    static readonly zs_friends_playing_switch = 0; // 好友在玩 TODO 暂缓 需求还没过来
    static readonly zs_reminder_switch = 0; // 温馨提示：微信假消息 点击取消后的 好友挑战
    static readonly zs_false_news_switch = 0; // 微信假消息
    static readonly zs_slide_jump_switch = 0; // 滑动触发跳转开关 
    static readonly zs_share_title = "这个是分享标题";
    static readonly zs_share_img = "这个是分享图片地址";
    static readonly zs_banner_adunit = "";
    static readonly zs_banner_adunit2 = "";
    static readonly zs_banner_adunit3 = "";
    static readonly zs_video_adunit = "";
    static readonly zs_full_screen_adunit = "";
    static readonly zs_gridAd_id = "";
    static readonly zs_click_award_num = "0"; // 游戏砸金蛋狂点次数（关卡模式中数字为关卡，无限模式中数字为次数，-1无限制，0无次数）
    static readonly zs_ready_click_num = "0"; // 通用砸金蛋狂点次数（关卡模式中数字为关卡，无限模式中数字为次数，-1无限制，0无次数）
    static readonly zs_click_award_since = 0; // 狂点在新用户几次游戏后出现
    static readonly zs_button_delay_time = 0; // 按钮延时开关（0为关，单位毫秒）
    static readonly zs_scene_value = "1005|1006|1011|1012|1013|1014|1017|1019|1020|1023|1024|1025|1030|1031|1032|1036|1042|1047|1048|1049|1053|1102|1129"; // 场景值屏蔽
    static readonly zs_revive_way = ""; //复活方式
    static readonly zs_revive_num = 0; //复活次数
    static readonly zs_system = "";
    static readonly zs_city = "上海市|广州市|深圳市|成都市|北京市";
    static readonly zs_time = "";
    static readonly zs_banner_banner_time = 1000
    static readonly zs_full_screen_banner_time = 3
    static readonly zs_banner_refresh_time = 30000
    static readonly zs_game_start_jump_switch = 0; // 首页导出位开关
    static readonly zs_full_screen_button_switch = 0; //全屏界面误触开关

    static readonly zs_native_click_switch = 0;
    static readonly zs_jump_time = 0;
    static readonly zs_start_video_switch = 0;
    static readonly zs_native_touch_switch = 0;
    static readonly zs_native_btn_text = "";
    static readonly zs_native_delay = 0;
    static readonly zs_native_close_switch = 0;
    static readonly zs_native_next_limit = 0;
    static readonly test_touch_switch = 0;
    static readonly zs_full_screen_jump = 0;
    static readonly zs_before_finsh_jump_switch = 0;
    static readonly zs_Fakerjump = 0;
    static readonly zs_finish_full_screen_switch = 0;
    static readonly zs_native_adunit = "";
    static readonly zs_native_newer_times = 0;
    static readonly zs_native_show_time = 0;
    static readonly zs_unmiss_text_time = 0;
    static readonly zs_native_limit = 1;
    static readonly zs_native_limit_time = 0;
    static readonly zs_native_touch_time = 0;
    static readonly zs_native_timeout = 0;
    static readonly zs_native_adunit_icon = "";
    static readonly zs_native_limit_10 = 0;
    static readonly zs_native_end_before_num = -1;
    static readonly zs_gamePortalAd_id = "";
    static readonly zs_quit_ad_id = "";
    static readonly zs_gameBannerAd_id = "";
    static readonly zs_onemin_show_ad_switch = 0;
    static readonly zs_show_banner_time = 0;
    static readonly zs_open_adunit = "";
    static readonly zs_native_adunit2 = ""
}